### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by ghost** [iamareebjamal/Kodis#2]
F-Droid is an repository  (*app store*) that only serves free/libre/open-source apps. We received a request for packaging your app at https://gitlab.com/fdroid/rfp/issues/103. If you object, please let me know and we will remove the app asap.

**Comment by iamareebjamal** [comment]
No problem at all. Delighted to be part of it :smile:

**Comment by ghost** [comment]
Ref: https://gitlab.com/fdroid/fdroiddata/commit/9304f32b8504b95be7891a3d1590f8377ed402c8
